services:
  - type: web
    name: car-ball-server
    env: node
    plan: free
    buildCommand: |
      npm install --production=false
      npm run build
    startCommand: node dist/server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: REDIS_URL
        value: # optional, leave blank unless needed
