services:
  - type: web
    name: web-service
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - fromGroup: cbv3-env

  - type: web
    name: static-site
    env: static
    plan: free
    buildCommand: |
      npm install
      npm run build
      cp -r dist public/dist
    staticPublishPath: public

envVarGroups:
  - name: cbv3-env
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: REDIS_URL
        value: ""
